// src/modal/ScanVaultModal.svelte
<script lang="ts">
	import { run } from 'svelte/legacy';

	import { onMount, onDestroy } from "svelte";
	import { MarkdownUIRenderer } from "../services/MarkdownUIRenderer";
	import { scanFilterForFilesNFolders } from "../utils/FiltersVerifier";
	import { t } from "../utils/lang/helper";
	import { taskElementsFormatter } from "../utils/TaskItemUtils";
	import ScanningVault from "../utils/ScanningVault";
	import { Notice } from 'obsidian';
	import type { taskItem } from 'src/interfaces/TaskItemProps';

	let { app, plugin } = $props();

	let scanningVault = new ScanningVault(app, plugin);
	let isRunning = $state(false);
	let terminalOutput = $state([]);
	let progress = $state(0);
	let showCollectedTasks = $state(false);
	let collectedTasks = $state({ Pending: {}, Completed: {} });
	let taskRendererRef = $state({});

	const runScan = async () => {
		isRunning = true;
		const files = app.vault.getMarkdownFiles();
		progress = 0; // Reset progress

		for (let i = 0; i < files.length; i++) {
			const file = files[i];

			const scanFilters = plugin.settings.data.globalSettings.scanFilters;
			if (scanFilterForFilesNFolders(file, scanFilters)) {
				terminalOutput = [
					...terminalOutput,
					`Scanning file: ${file.path}`,
				];
				await scanningVault.extractTasksFromFile(
					file,
					scanningVault.tasks,
					scanFilters,
				);
			}

			progress = ((i + 1) / files.length) * 100; // Update progress
		}

		collectedTasks = scanningVault.tasks;
		new Notice(t(64));
		scanningVault.saveTasksToFile();
	};

	const toggleView = () => {
		showCollectedTasks = !showCollectedTasks;
	};

	onMount(() => {
		// Set up component-related initialization here if needed
	});

	onDestroy(() => {
		// Clean up resources if necessary
	});

	run(() => {
		if (showCollectedTasks) {
			Object.keys(collectedTasks.Pending).forEach((filePath) => {
				const tasks = collectedTasks.Pending[filePath];
				tasks.forEach((task: taskItem, taskIndex: number) => {
					const newTaskContent = {
						...task,
						title: task.title,
						body: task.body,
						due: task.due,
						tags: task.tags,
						time: task.time,
						priority: task.priority,
					};

					const formattedContent = taskElementsFormatter(
						plugin,
						newTaskContent,
					);

					const uniqueKey = `${filePath}-task-${taskIndex}`;
					const descElement = taskRendererRef[uniqueKey];

					if (descElement && formattedContent !== "") {
						descElement.innerHTML = "";
						MarkdownUIRenderer.renderTaskDisc(
							app,
							formattedContent,
							descElement,
							task.filePath,
							null,
						);
					}
				});
			});
		}
	});
</script>

<div class="scanVaultModalHome">
	<h2>{t(65)}</h2>
	<p>{t(66)}</p>
	<p>{t(67)}</p>
	<p>{t(68)}</p>

	<div class="scanVaultModalHomeSecondSection">
		<div class="scanVaultModalHomeSecondSectionProgressBarContainer">
			<progress
				max="100"
				value={progress}
				style="width: 100%; height: 35px;"
			></progress>
		</div>
		<button
			class="scanVaultModalHomeSecondSectionButton"
			onclick={runScan}
			disabled={isRunning}
		>
			{isRunning ? progress.toFixed(0) : t(69)}
		</button>
	</div>

	<div class="scanVaultModalHomeThirdSection">
		<div
			class={`scanVaultModalHomeTerminal ${
				showCollectedTasks
					? "scanVaultModalHomeTerminalSlideOut"
					: "scanVaultModalHomeTerminalSlideIn"
			}`}
		>
			{#each terminalOutput as line, index}
				<div key={index}>{line}</div>
			{/each}
		</div>

		<div
			class={`scanVaultModalHomeTasksCollected ${
				showCollectedTasks ? "slideIn" : "slideOut"
			}`}
		>
			{#each Object.keys(collectedTasks.Pending) as filePath, index}
				<div key={index}>
					<h3>{filePath}</h3>
					<div>
						{#each collectedTasks.Pending[filePath] as task, taskIndex}
							<div key={taskIndex}>
								<div
									bind:this={taskRendererRef[
										`${filePath}-task-${taskIndex}`
									]}
									id={`${filePath}-task-${taskIndex}`}
								></div>
							</div>
						{/each}
					</div>
				</div>
			{/each}
		</div>
	</div>

	<button class="scanVaultModalHomeToggleButton" onclick={toggleView}>
		{showCollectedTasks ? t(70) : t(71)}
	</button>
</div>

// src/modal/ScanVaultModal.tsx
// /src/components/ScanVaultModal.tsx

import { App, Component, Modal, Notice } from "obsidian";
import React, { useEffect, useRef, useState } from "react";
import { taskItem, tasksJson } from "src/interfaces/TaskItemProps";

import { MarkdownUIRenderer } from "src/services/MarkdownUIRenderer";
import ReactDOM from "react-dom/client";
import { ScanningVault } from "src/utils/ScanningVault";
import TaskBoard from "main";
import { scanFilterForFilesNFolders } from "src/utils/FiltersVerifier";
import { t } from "src/utils/lang/helper";
import { taskContentFormatter } from "src/utils/TaskContentFormatter";

const ScanVaultModalContent: React.FC<{ app: App, plugin: TaskBoard, scanningVault: ScanningVault }> = ({ app, plugin, scanningVault }) => {

	const [isRunning, setIsRunning] = useState(false);
	const [terminalOutput, setTerminalOutput] = useState<string[]>([]);
	const [progress, setProgress] = useState(0);
	const [showCollectedTasks, setShowCollectedTasks] = useState(false);
	const [collectedTasks, setCollectedTasks] = useState<tasksJson>({
		Pending: {},
		Completed: {},
	});

	const runScan = async () => {
		setIsRunning(true);
		const files = app.vault.getMarkdownFiles();
		setProgress(0); // Reset progress

		for (let i = 0; i < files.length; i++) {
			const file = files[i];

			const scanFilters = plugin.settings.data.globalSettings.scanFilters;
			if (scanFilterForFilesNFolders(file, scanFilters)) {
				setTerminalOutput((prev) => [...prev, `Scanning file: ${file.path}`]);
				await scanningVault.extractTasksFromFile(file, scanningVault.tasks, scanFilters);
			}

			setProgress(((i + 1) / files.length) * 100); // Update progress
		}

		setCollectedTasks(scanningVault.tasks);
		// setIsRunning(false);
		new Notice(t("vault-scanning-complete"));
		scanningVault.saveTasksToFile();
	};

	const toggleView = () => {
		setShowCollectedTasks(!showCollectedTasks);
	};

	const componentRef = useRef<Component | null>(null);
	useEffect(() => {
		// Initialize Obsidian Component on mount
		componentRef.current = plugin.view;
	}, []);

	const taskRendererRef = useRef<{ [key: string]: HTMLDivElement | null }>({});
	useEffect(() => {
		// Render tasks in collectedTasks when the view is toggled to show
		if (showCollectedTasks) {
			Object.keys(collectedTasks.Pending).forEach(filePath => {
				const tasks = collectedTasks.Pending[filePath];
				tasks.forEach((task, taskIndex) => {
					const newTaskContent: taskItem = {
						...task,
						title: task.title,
						body: task.body,
						due: task.due,
						tags: task.tags,
						time: task.time,
						priority: task.priority,
					};

					const formatedContent = taskContentFormatter(plugin, newTaskContent);

					const uniqueKey = `${filePath}-task-${taskIndex}`;
					const descElement = taskRendererRef.current[uniqueKey];

					if (descElement && formatedContent !== "") {
						descElement.empty();
						// Render task description using MarkdownUIRenderer
						MarkdownUIRenderer.renderTaskDisc(
							app,
							formatedContent,
							descElement,
							task.filePath,
							componentRef.current
						);
					}
				});
			});
		}
	}, [showCollectedTasks, collectedTasks]);

	return (
		<div className="scanVaultModalHome">
			<h2>{t("scan-tasks-from-the-vault")}</h2>
			<div className="setting-item-description">{t("scan-tasks-from-the-vault-description-1")}</div>
			<div className="setting-item-description">{t("scan-tasks-from-the-vault-description-2")}</div>
			<div className="setting-item-description">{t("scan-tasks-from-the-vault-description-3")}</div>

			<div className="scanVaultModalHomeSecondSection" >
				<div className="scanVaultModalHomeSecondSectionProgressBarContainer">
					<progress max="100" value={progress} style={{ width: "100%", height: '35px' }}></progress>
				</div>
				<button className="scanVaultModalHomeSecondSectionButton" onClick={runScan} disabled={isRunning}>
					{isRunning ? progress.toFixed(0) : t("run")}
				</button>
			</div>

			<div className="scanVaultModalHomeThirdSection">
				<div className={`scanVaultModalHomeTerminal ${showCollectedTasks ? 'scanVaultModalHomeTerminalSlideOut' : 'scanVaultModalHomeTerminalSlideIn'}`}>
					{terminalOutput.map((line, index) => (
						<div key={index}>{line}</div>
					))}
				</div>
				<div className={`scanVaultModalHomeTasksCollected ${showCollectedTasks ? 'slideIn' : 'slideOut'}`}>
					{Object.keys(collectedTasks.Pending).map((filePath, index) => (
						<div key={index}>
							<h3>{filePath}</h3>
							<div>
								{collectedTasks.Pending[filePath].map((task: any, taskIndex: number) => {
									const uniqueKey = `${filePath}-task-${taskIndex}`;
									return (
										<div key={taskIndex}>
											<div
												ref={(descEl) => (taskRendererRef.current[uniqueKey] = descEl)}
												id={uniqueKey}
											/>
										</div>
									);
								})}
							</div>
						</div>
					))}
				</div>
			</div>

			<button className="scanVaultModalHomeToggleButton" onClick={toggleView}>
				{showCollectedTasks ? t("hide-collected-tasks") : t("show-collected-tasks")}
			</button>
		</div>
	);
}

export class ScanVaultModal extends Modal {
	scanningVault: ScanningVault;
	plugin: TaskBoard;

	constructor(app: App, plugin: TaskBoard) {
		super(app);
		this.plugin = plugin;
		this.scanningVault = new ScanningVault(app, plugin);
	}

	onOpen() {
		const { contentEl } = this;
		contentEl.empty();

		this.modalEl.setAttribute('data-type', 'task-board-view');
		contentEl.setAttribute('data-type', 'task-board-view');

		const root = ReactDOM.createRoot(this.contentEl);

		root.render(<ScanVaultModalContent
			app={this.app}
			plugin={this.plugin}
			scanningVault={this.scanningVault}
		/>);

		// Render React component inside the Obsidian modal
		// this.renderModal();
	}

	onClose(): void {
		this.contentEl.empty();
	}
}
